const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
function setup({names=['a_ai'],quota=100,failMail=false,failCommit=false,ack=null}={}) {
 const requests=[],mail=[],properties={};if(ack)properties.ARVUS_PENDING_ACK=JSON.stringify(ack);
 const root='projects/arvus-basvuru/databases/(default)/documents/applications/';
 let released=false;
 const context={console:{log(){}},ScriptApp:{getOAuthToken:()=> 'test-only'},LockService:{getScriptLock:()=>({tryLock:()=>true,releaseLock(){released=true;}})},PropertiesService:{getScriptProperties:()=>({getProperty:k=>properties[k],setProperty:(k,v)=>{properties[k]=v;},deleteProperty:k=>delete properties[k]})},MailApp:{getRemainingDailyQuota:()=>quota,sendEmail:m=>{if(failMail)throw Error('mail failed');mail.push(m);}},UrlFetchApp:{fetch:(url,options)=>{const body=JSON.parse(options.payload);requests.push({url,body});let result=[];let status=200;if(url.endsWith(':runQuery'))result=names.map(n=>({document:{name:root+n}}));if(url.endsWith(':batchGet'))result=body.documents.map(n=>({found:{name:n}}));if(url.endsWith(':commit')&&failCommit){status=503;result={error:{message:'temporary error'}};}return {getResponseCode:()=>status,getContentText:()=>JSON.stringify(result)};}}};
 vm.createContext(context);vm.runInContext(fs.readFileSync('notifications/Code.gs','utf8'),context);
 return {run:()=>context.checkApplications(),requests,mail,properties,released:()=>released};
}
test('notification contains count and private panel link only, then acknowledges records',()=>{const t=setup({names:['a_ai','b_ew']});t.run();assert.equal(t.mail.length,1);assert.equal(t.mail[0].to,'remziazakli@gmail.com');assert.match(t.mail[0].body,/2 yeni başvuru/);assert.match(t.mail[0].body,/admin.html/);assert(!t.mail[0].body.includes('a_ai'));assert.equal(t.requests.at(-1).body.writes.length,2);assert.equal(t.requests[0].body.structuredQuery.select.fields[0].fieldPath,'__name__');assert.equal(t.properties.ARVUS_PENDING_ACK,undefined);assert(t.released());});
test('empty queue and exhausted quota do not send or mark records',()=>{for(const config of [{names:[]},{quota:0}]){const t=setup(config);t.run();assert.equal(t.mail.length,0);assert(!t.requests.some(r=>r.url.endsWith(':commit')));}});
test('mail failure leaves records pending and always releases lock',()=>{const t=setup({failMail:true});assert.throws(t.run,/mail failed/);assert(!t.requests.some(r=>r.url.endsWith(':commit')));assert(t.released());});
test('failed acknowledgement is remembered and recovered before new mail',()=>{const t=setup({failCommit:true});assert.throws(t.run,/503/);assert.deepEqual(JSON.parse(t.properties.ARVUS_PENDING_ACK),['a_ai']);const recovered=setup({ack:['a_ai'],names:[]});recovered.run();assert.equal(recovered.mail.length,0);assert(recovered.requests[0].url.endsWith(':batchGet'));assert.equal(recovered.properties.ARVUS_PENDING_ACK,undefined);});
