import {connect,OWNER_EMAILS,doc,collection,query,where,or,limit,onSnapshot,getDocFromServer,getDocsFromServer,runTransaction,serverTimestamp,documentId,orderBy,startAfter} from './firebase.js';
import {ROLES,STATUS,stamp,escapeHTML as E,localDay,safeURL,notices,canManage,teamDefaults} from './model.js';

const $=id=>document.getElementById(id);
const blank=()=>({access:[],members:[],teams:[],tasks:[],routes:[],enrollments:[],steps:{},equipment:[],loans:[],seen:[]});
let service,user,grant,data=blank(),epoch=0,grantOff=null,subscriptions=[],stepSubscriptions=new Map(),pending=0,cap=200,view='today',search='',filter='',modalMode='',modalId='',formAction=null,busy=false,toastTimer,watchdog,loaded=false;
const email=()=>user?.email||'';
const admin=()=>grant?.role==='admin';
const manager=()=>grant?.role==='admin'||grant?.role==='mentor';
const teamName=id=>data.teams.find(t=>t.id===id)?.name||id||'Takım yok';
const personName=id=>data.members.find(m=>m.email===id)?.name||data.access.find(m=>m.id===id)?.name||(id===email()?grant?.name:'')||id;
const date=v=>v?(v.toDate?v.toDate():new Date(typeof v==='string'&&v.length===10?v+'T12:00:00':v)).toLocaleDateString('tr-TR',{day:'numeric',month:'short'}):'—';
const plusDays=n=>{const d=new Date();d.setDate(d.getDate()+n);return d.toLocaleDateString('sv-SE');};
const button=(label,act,id='',primary=false)=>`<button class="btn ${primary?'primary':''}" data-action="${act}" data-id="${E(id)}">${label}</button>`;
const tag=(label,cls='')=>`<span class="tag ${cls}">${E(label)}</span>`;
const empty=(title,text)=>`<div class="empty"><h3>${E(title)}</h3><p>${E(text)}</p></div>`;
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),6000);}
function errText(e){const code=e?.code||'';if(code.includes('permission-denied'))return 'Bu işlem için yetkin yok veya kaydın durumu değişti. Sayfayı yenileyip tekrar dene.';if(code.includes('unavailable')||code.includes('deadline'))return 'Sunucuya ulaşılamadı. İnternet bağlantını kontrol et.';if(code.includes('popup-closed'))return 'Giriş penceresi kapatıldı. Tekrar deneyebilirsin.';if(code.includes('unauthorized-domain'))return 'Bu adres Google girişi için yetkilendirilmemiş. Firebase Authentication alan adlarını kontrol et.';if(code.includes('popup-blocked'))return 'Tarayıcı giriş penceresini engelledi. Bu sekmede devam edebilirsin.';return e?.message||'İşlem tamamlanamadı.';}
function stopData(){epoch++;for(const off of subscriptions)off();subscriptions=[];for(const off of stepSubscriptions.values())off();stepSubscriptions.clear();data=blank();grant=null;loaded=false;pending=0;clearTimeout(watchdog);if($('modal').open)$('modal').close();modalMode='';formAction=null;$('content').replaceChildren();$('modal-content').replaceChildren();$('modal-title').textContent='';$('page-actions').replaceChildren();$('navigation').replaceChildren();$('profile-name').textContent='';$('profile-role').textContent='';$('profile-avatar').textContent='';$('unread').textContent='0';}
function gate(message,hasAccount=false){$('portal').hidden=true;$('auth-screen').hidden=false;$('auth-message').textContent=message;$('login').disabled=!service;$('login').textContent=hasAccount?'Bağlantıyı tekrar kontrol et':'Google ile giriş yap ↗';$('auth-logout').hidden=!hasAccount;}
function lock(message){stopData();gate(message,!!user);}
function accessSignature(a){return JSON.stringify([a.role,a.teamIds,a.active,a.name]);}
async function attachUser(nextUser){
  grantOff?.();grantOff=null;stopData();user=nextUser;
  if(!user){gate('Takıma kayıtlı Google hesabınla giriş yap.');return;}
  gate('Hesap yetkin kontrol ediliyor…',true);
  const mine=email();
  grantOff=onSnapshot(doc(service.db,'portalAccess',mine),{includeMetadataChanges:true},snapshot=>{
    if(email()!==mine||snapshot.metadata.fromCache||snapshot.metadata.hasPendingWrites)return;
    const a=snapshot.exists()?{...snapshot.data(),id:mine}:null;
    const effective=OWNER_EMAILS.includes(mine)?{...(a||{}),name:a?.name||user.displayName||mine,role:'admin',teamIds:a?.teamIds||[],active:true}:a;
    if(!effective?.active){lock('Bu Google hesabının takım erişimi yok veya pasife alınmış. Yöneticiye e-posta adresini ilet.');return;}
    if(!grant||accessSignature(grant)!==accessSignature(effective))startData(effective);
  },e=>lock(errText(e)));
}
function listen(q,receive){const token=epoch;pending++;let first=true;const off=onSnapshot(q,{includeMetadataChanges:true},snap=>{if(token!==epoch||snap.metadata.fromCache||snap.metadata.hasPendingWrites)return;if(first){first=false;pending--;}receive(snap);if(!pending){loaded=true;clearTimeout(watchdog);$('loading').hidden=true;}render();refreshDetail();},e=>{if(token===epoch)lock(errText(e));});subscriptions.push(off);return off;}
function watchList(name,conditions=[]){listen(query(collection(service.db,'portal'+name[0].toUpperCase()+name.slice(1)),...conditions,limit(cap)),snap=>{data[name]=snap.docs.map(d=>({...d.data(),id:d.id}));if(name==='enrollments')watchSteps();});}
function watchSteps(){const live=new Set(data.enrollments.map(e=>e.id));for(const [id,off] of stepSubscriptions)if(!live.has(id)){off();stepSubscriptions.delete(id);delete data.steps[id];}
  for(const en of data.enrollments)if(!stepSubscriptions.has(en.id)){const token=epoch;const off=onSnapshot(query(collection(service.db,'portalEnrollments',en.id,'steps'),limit(15)),{includeMetadataChanges:true},s=>{if(token!==epoch||s.metadata.fromCache||s.metadata.hasPendingWrites)return;data.steps[en.id]=s.docs.map(d=>({...d.data(),id:d.id})).sort((a,b)=>a.index-b.index);render();refreshDetail();},e=>{if(token===epoch)lock(errText(e));});stepSubscriptions.set(en.id,off);}}
function startData(a){stopData();grant=a;const token=epoch;$('auth-screen').hidden=true;$('portal').hidden=false;$('loading').hidden=false;$('connection').textContent='Ortak kayıtlar';
  const my=email(),lead=a.role==='mentor'&&a.teamIds.length;
  watchList('teams');watchList('routes');watchList('equipment');
  if(admin()){watchList('access');watchList('members');watchList('tasks');watchList('enrollments');watchList('loans');}
  else{
    if(lead)watchList('members',[where('teamIds','array-contains-any',a.teamIds)]);
    else listen(doc(service.db,'portalMembers',my),s=>{data.members=s.exists()?[{...s.data(),id:s.id}]:[];});
    watchList('tasks',[lead?or(where('assignee','==',my),where('teamId','in',a.teamIds)):where('assignee','==',my)]);
    watchList('enrollments',[lead?or(where('memberEmail','==',my),where('teamId','in',a.teamIds)):where('memberEmail','==',my)]);watchList('loans',[where('memberEmail','==',my)]);
  }
  listen(query(collection(service.db,'portalSeen',my,'items'),limit(2000)),s=>{data.seen=s.docs.map(d=>d.id);});
  watchdog=setTimeout(()=>{if(token===epoch&&pending)lock('Bağlantı zaman aşımına uğradı. Tekrar kontrol edebilirsin.');},18000);render();
}
async function recheck(){if(!user)return;const snap=await getDocFromServer(doc(service.db,'portalAccess',email()));if(!OWNER_EMAILS.includes(email())&&(!snap.exists()||!snap.data().active)){lock('Takım erişimin kapatılmış.');return;}if(!grant)await attachUser(user);}
function assertSession(token){if(token!==epoch||!grant||!user)throw Error('Oturum değişti. İşlem durduruldu.');}
function ref(path){return doc(service.db,...path.split('/'));}
async function change(path,values,expected=null,create=false){const token=epoch;assertSession(token);return runTransaction(service.db,async tx=>{assertSession(token);const r=ref(path),s=await tx.get(r);if(create&&s.exists())throw Error('Bu kayıt zaten var.');if(!create&&!s.exists())throw Error('Kayıt bulunamadı.');if(expected!==null&&stamp(s.data()?.updatedAt)!==expected)throw Error('Bu kayıt başka bir kullanıcı tarafından değiştirildi. Pencereyi kapatıp yeniden aç.');assertSession(token);const payload={...values,updatedAt:serverTimestamp()};if(create)tx.set(r,payload);else tx.update(r,payload);});}
async function execute(fn,close=true){if(busy)return;busy=true;const token=epoch;document.body.classList.add('saving');const buttons=[...$('modal').querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);$('form-error')&&($('form-error').textContent='');try{await fn();assertSession(token);if(close){$('modal').close();modalMode='';}toast('Sunucuya kaydedildi.');return true;}catch(e){if(token===epoch){if($('form-error'))$('form-error').textContent=errText(e);else toast(errText(e));}}finally{busy=false;document.body.classList.remove('saving');buttons.forEach(b=>b.disabled=false);}}
function navItems(){return [['today','Bugün','☀'],['tasks','Görevler','✓'],['learning','Öğrenme rotaları','▤'],['equipment','Ekipman & zimmet','◇'],['inbox','Bildirim kutusu','◉'],...(manager()?[['members','Üyeler','♧']]:[]),...(admin()?[['teams','Takımlar & birimler','▦'],['settings','Yönetim & yedek','⚙']]:[])];}
function go(next){view=navItems().some(([id])=>id===next)?next:'today';location.hash=view;search='';filter='';$('sidebar').classList.remove('open');render();}
function render(){if(!grant)return;const nav=navItems();if(!nav.some(([id])=>id===view))view='today';$('navigation').innerHTML=nav.map(([id,label,icon])=>`<button class="navitem ${view===id?'active':''}" data-nav="${id}"><span aria-hidden="true">${icon}</span>${label}</button>`).join('');$('title').textContent=nav.find(([id])=>id===view)?.[1];$('crumb').textContent=$('title').textContent;$('profile-name').textContent=grant.name;$('profile-role').textContent=ROLES[grant.role];$('profile-avatar').textContent=grant.name.split(' ').map(x=>x[0]).slice(0,2).join('');
  $('subtitle').textContent=({today:'Kendi işlerin, öğrenme yolculuğun ve takımınla bir sonraki adım.',tasks:'Görevi ilerlet, çıktını paylaş, takıldığın yeri birlikte çöz.',learning:'Üretirken öğren. Her adımda somut bir çıktı.',equipment:'Ortak ekipmanların teslim ve iade takibi.',inbox:'Sana ait güncellemeler ve bekleyen işler.',members:'Üyeler, Google hesapları ve takım erişimleri.',teams:'Farklı disiplinler. Ortak hedefler.',settings:'Çalışma alanı, aktarım ve güvenli yedek.'})[view];
  const actions=view==='tasks'&&manager()?button('Görev oluştur','task-new','',true):view==='members'&&admin()?button('Üye ekle','member-new','',true):view==='teams'?button('Takım / birim ekle','team-new','',true):view==='learning'&&manager()?button('Rota oluştur','route-new')+button('Üyeye rota ata','enroll-new','',true):view==='equipment'&&admin()?button('Ekipman ekle','asset-new','',true):'';$('page-actions').innerHTML=actions;
  const unread=notices(data,email(),admin()).filter(n=>!data.seen.includes(n.id));$('unread').textContent=String(unread.length);
  $('content').innerHTML=({today:todayView,tasks:tasksView,learning:learningView,equipment:equipmentView,inbox:inboxView,members:membersView,teams:teamsView,settings:settingsView})[view]();
  if(Object.keys(data).some(k=>Array.isArray(data[k])&&k!=='seen'&&data[k].length>=cap))$('content').insertAdjacentHTML('beforeend',`<div class="notice-card">İlk ${cap} kayıt yüklendi. ${cap<2000?button('Daha fazla yükle','load-more'):'Tüm kayıtlar için yönetici yedeğini kullan.'}</div>`);
}
function dueTag(v){return tag(v?`${v<localDay()?'Gecikti · ':v===localDay()?'Bugün · ':''}${date(v)}`:'Tarih yok',v&&v<=localDay()?'pending':'');}
function taskCard(t){return `<article class="task"><div class="op-meta">${tag(teamName(t.teamId))}${dueTag(t.due)}</div><h3>${E(t.title)}</h3><p>${E(t.description||'Açıklama eklenmedi.')}</p>${t.blocker?`<div class="op-danger">Destek gerekiyor: ${E(t.blocker)}</div>`:''}<div class="task-meta"><span>${E(personName(t.assignee))}</span>${tag(STATUS[t.status],t.status)}</div><div class="actions" style="margin-top:15px">${button('Ayrıntı & yorumlar','task-open',t.id,true)}</div></article>`;}
function todayView(){const mine=data.tasks.filter(t=>t.assignee===email()&&t.status!=='done').sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999')),loans=data.loans.filter(l=>l.memberEmail===email()&&!l.returnedAt),enrolls=data.enrollments.filter(e=>e.memberEmail===email()),needsReview=data.enrollments.filter(e=>e.mentorEmail===email()&&(data.steps[e.id]||[]).some(s=>s.status==='pending'));return `<section class="focus-hero"><div><div class="eyebrow">KÜÇÜK ADIMLAR. GERÇEK ÇIKTILAR.</div><h2>Merhaba, ${E(grant.name.split(' ')[0])}.</h2><p>${mine.length?`${mine.length} açık görevin var. Bir sonraki çıktını belirleyip başlayabilirsin.`:'Şu an sana atanmış açık görev yok. Öğrenme rotalarını ve takımın ihtiyaçlarını kontrol edebilirsin.'}</p></div><span class="tag">${E(ROLES[grant.role])}</span></section>${admin()&&!data.teams.length&&loaded?`<div class="notice-card"><strong>ARVUS çalışma alanını başlat</strong><p>Yarışma takımları ve mevcut yönetici hesapları oluşturulsun.</p>${button('Çalışma alanını başlat','bootstrap','',true)}</div>`:''}<div class="stats">${[[mine.length,'Açık görev'],[mine.filter(t=>t.blocker).length,'Destek bekleyen'],[enrolls.length,'Öğrenme rotası'],[loans.length,'Üzerindeki ekipman']].map(([n,title])=>`<div class="focus-card"><span class="stat-top">${title}</span><div class="op-stat">${n}</div></div>`).join('')}</div><div class="op-grid"><section class="panel op-panel"><h2>Odak listem</h2>${mine.map(taskCard).join('')||empty('Yeni bir adıma hazırsın','Takım sorumlun sana görev atadığında burada görünecek.')}</section><div class="op-stack"><section class="panel op-panel"><h2>Öğrenmeye devam</h2>${enrolls.map(e=>`<div class="op-row"><div><strong>${E(e.name)}</strong><small>${(data.steps[e.id]||[]).filter(s=>s.status==='done').length}/${e.stepCount} adım onaylandı</small></div>${button('Aç','enroll-open',e.id)}</div>`).join('')||'<p class="op-muted">Henüz rota atanmadı.</p>'}${needsReview.length?'<h3 style="margin-top:20px;font-size:14px">İncelemen bekleniyor</h3>'+needsReview.map(e=>`<div class="op-row"><div><strong>${E(personName(e.memberEmail))}</strong><small>${E(e.name)}</small></div>${button('İncele','enroll-open',e.id)}</div>`).join(''):''}</section><section class="panel op-panel"><h2>İade takvimim</h2>${loans.map(l=>`<div class="op-row"><div><strong>${E(l.equipmentName)}</strong>${dueTag(l.due)}</div>${l.returnRequested?tag('İade onayı bekliyor','pending'):button('İade talebi','return-request',l.id)}</div>`).join('')||'<p class="op-muted">Üzerinde ekipman yok.</p>'}</section></div></div>`;}
function toolbar(placeholder,options=[]){return `<div class="op-toolbar"><label class="field-search"><input id="search" aria-label="Listede ara" placeholder="${placeholder}" value="${E(search)}"></label>${options.length?`<select class="control" id="filter" aria-label="Liste filtresi"><option value="">Tümü</option>${options.map(([id,name])=>`<option value="${E(id)}" ${filter===id?'selected':''}>${E(name)}</option>`).join('')}</select>`:''}</div>`;}
function matches(...s){return s.join(' ').toLocaleLowerCase('tr').includes(search.toLocaleLowerCase('tr'));}
function tasksView(){const list=data.tasks.filter(t=>matches(t.title,personName(t.assignee))&&(!filter||t.teamId===filter));return toolbar('Görev veya sorumlu ara...',data.teams.map(t=>[t.id,t.name]))+`<div class="board">${Object.entries(STATUS).map(([id,name])=>`<section class="board-column"><div class="column-title"><span>${name}</span><span>${list.filter(t=>t.status===id).length}</span></div>${list.filter(t=>t.status===id).map(taskCard).join('')||'<p class="ops-empty">Bu aşamada görev yok.</p>'}</section>`).join('')}</div>`;}
function learningView(){return `<div class="group-grid">${data.enrollments.map(en=>{const steps=data.steps[en.id]||[],done=steps.filter(s=>s.status==='done').length;return `<article class="panel route-card"><div class="op-meta">${tag(done===en.stepCount?'Tamamlandı':'Öğreniyor',done===en.stepCount?'done':'todo')}${dueTag(en.due)}</div><h2>${E(en.name)}</h2><p>${E(personName(en.memberEmail))}</p><div class="track"><i style="width:${done/en.stepCount*100}%;background:var(--blue)"></i></div><p>${done}/${en.stepCount} onay · Mentor: ${E(personName(en.mentorEmail))}</p><div class="actions">${button('Rotayı aç','enroll-open',en.id,true)}</div></article>`}).join('')}</div>${!data.enrollments.length?empty('Henüz atanmış rota yok','Takım sorumlusu bir üye, mentor ve hedef tarih seçerek rota atayabilir.'):''}<div class="panel-head"><h2>Rota kütüphanesi</h2></div><div class="group-grid">${data.routes.map(r=>`<article class="panel route-card">${tag(teamName(r.teamId))}<h2>${E(r.name)}</h2><p>${E(r.description)}</p><p style="margin-top:15px">${r.steps.length} uygulamalı adım</p>${canManage(grant,r.teamId)?`<div class="actions">${button('Düzenle','route-edit',r.id)}${button('Üyeye ata','enroll-new',r.id,true)}</div>`:''}</article>`).join('')}</div>`;}
function equipmentView(){const items=data.equipment.filter(a=>matches(a.name,a.code,a.location)&&(!filter||(filter==='loaned'?!!a.activeLoanId:filter==='ready'?!a.activeLoanId&&a.condition==='ready':a.condition==='maintenance')));return toolbar('Ekipman, konum veya envanter kodu ara...',[['ready','Kullanıma hazır'],['loaned','Zimmette'],['maintenance','Bakımda']])+`<div class="equipment-grid">${items.map(a=>{const l=data.loans.find(l=>l.id===a.activeLoanId);return `<article class="panel equipment-card"><div class="op-meta"><span class="asset-code">${E(a.code)}</span>${tag(a.activeLoanId?'Zimmette':a.condition==='ready'?'Hazır':'Bakımda',a.activeLoanId?'pending':a.condition==='ready'?'done':'blocked')}</div><h2>${E(a.name)}</h2><p class="op-muted">${E(a.location)}</p>${l?`<p class="op-muted" style="margin-top:15px">${E(l.memberName)} · ${date(l.due)}${l.returnRequested?' · İade talebi var':''}</p>`:''}<div class="actions">${button('Ayrıntı','asset-open',a.id)}${admin()&&!a.activeLoanId&&a.condition==='ready'?button('Zimmet ver','loan-new',a.id,true):''}${admin()&&l?button('İade al','loan-return',l.id,true):''}${!admin()&&l&&!l.returnRequested?button('İade talebi','return-request',l.id):''}</div></article>`}).join('')}</div>${!items.length?empty('Ekipman bulunamadı','Yönetici ekipman eklediğinde burada görünecek.'):''}`;}
function inboxView(){const list=notices(data,email(),admin());return `<p class="op-help" style="margin-bottom:20px">Görevlerin ve öğrenme adımlarının en son güncellemeleri burada görünür. Bildirimler uygulama içindedir.</p><section class="panel op-panel">${list.map(n=>`<div class="op-row ${data.seen.includes(n.id)?'read-notice':''}"><span class="notice-dot ${data.seen.includes(n.id)?'seen':''}"></span><div><strong>${E(n.title)}</strong><small>${E(n.detail)} · ${date(n.at)}</small></div>${button('Aç','notice-open',n.id)}${!data.seen.includes(n.id)?button('Okundu','notice-read',n.id):''}</div>`).join('')||empty('Şimdilik sakin','Yeni görev ve geri bildirimler burada görünecek.')}</section>`;}
function membersView(){const list=data.members.filter(m=>matches(m.name,m.email,m.department)&&(!filter||m.teamIds.includes(filter)));return toolbar('İsim, e-posta veya bölüm ara...',data.teams.map(t=>[t.id,t.name]))+`<section class="panel table-wrap"><table><thead><tr><th>Üye</th><th>Takımlar</th><th>Rol / erişim</th><th></th></tr></thead><tbody>${list.map(m=>{const a=data.access.find(a=>a.id===m.email);return `<tr><td><strong>${E(m.name)}</strong><small style="display:block">${E(m.email)}</small></td><td>${m.teamIds.map(t=>tag(teamName(t))).join(' ')}</td><td>${a?tag(a.active?ROLES[a.role]:'Erişim kapalı',a.active?'done':'blocked'):E(m.jobTitle||'Üye')}</td><td>${admin()?button('Düzenle','member-edit',m.email):button('Bilgiler','member-open',m.email)}</td></tr>`}).join('')}</tbody></table>${!list.length?empty('Üye bulunamadı','Google e-posta adresiyle bir üye ekleyebilirsin.'):''}</section>`;}
function teamsView(){return `<div class="group-grid">${data.teams.map(t=>`<article class="panel route-card">${tag(t.kind==='team'?'Yarışma takımı':'Çalışma birimi',t.color)}<h2>${E(t.name)}</h2><p>${E(t.description)}</p><div class="actions">${button('Düzenle','team-edit',t.id)}</div></article>`).join('')}</div>`;}
function settingsView(){return `<div class="data-grid"><section class="panel data-card"><h2>Hesap ve erişim</h2><p>Google hesabı: ${E(email())}<br>Yetki: ${E(ROLES[grant.role])}</p><p>Üyeler bölümünden e-posta, rol ve takım seç. Erişimi kapatılan hesaplar portal verilerine ulaşamaz.</p>${button('Üyeleri yönet','goto-members','',true)}</section><section class="panel data-card"><h2>Ortak kayıtları yedekle</h2><p>Takımlar, üyeler, görevler, yorumlar, öğrenme rotaları ve ekipman geçmişini sunucudan JSON dosyasına indir.</p>${button('Tam yedek indir','backup','',true)}<p class="op-help">Yedek kişisel bilgi içerir; herkese açık paylaşma. Bildirimlerin okundu bilgisi kişiseldir ve bu yedeğe dahil değildir.</p></section><section class="panel data-card"><h2>Başvurudan üyeliğe</h2><p>Başvuru panelinin JSON dosyasını seç. Kişileri önce erişimi kapalı olarak ekle; ardından Google e-postasını kontrol edip erişimini aç.</p>${button('Başvuru JSON dosyası seç','import-apps')}<input type="file" id="applications-file" accept="application/json,.json" hidden><p class="op-help">Mevcut üyeler değiştirilmez. Bu işlem e-posta göndermez.</p></section><section class="panel data-card"><h2>Çalışma alanı başlangıcı</h2><p>İlk kurulumda yarışma takımları, üç örnek öğrenme rotası ve mevcut yönetici hesaplarını oluştur. Var olan kayıtların üzerine yazılmaz.</p>${OWNER_EMAILS.includes(email())?button('Başlangıç kayıtlarını oluştur','bootstrap'):tag('Sistem sahibi hesabı gerekli')}</section></div>`;}
function field(label,name,value='',type='text',required=false,max=160){return `<label class="form-field"><span>${label}</span><input name="${name}" type="${type}" value="${E(value)}" maxlength="${max}" ${required?'required':''}></label>`;}
function area(label,name,value='',max=3000){return `<label class="form-field wide"><span>${label}</span><textarea name="${name}" maxlength="${max}">${E(value)}</textarea></label>`;}
function select(label,name,value,options){return `<label class="form-field"><span>${label}</span><select name="${name}" required>${options.map(([id,title])=>`<option value="${E(id)}" ${id===value?'selected':''}>${E(title)}</option>`).join('')}</select></label>`;}
function openModal(title,html,mode='detail',id=''){$('modal-title').textContent=title;$('modal-content').innerHTML=html;modalMode=mode;modalId=id;if(!$('modal').open)$('modal').showModal();}
function form(title,html,fn){formAction=fn;openModal(title,`<form id="form"><div class="form-grid">${html}</div><p class="error" role="alert" id="form-error"></p><div class="form-actions"><button type="button" class="btn" data-action="modal-close">Vazgeç</button><button class="btn primary" type="submit">Kaydet</button></div></form>`,'form');}
function activeMembers(team){return data.members.filter(m=>(!team||m.teamIds.includes(team))&&(data.access.find(a=>a.id===m.email)?.active??true));}
function editableTeams(){return data.teams.filter(t=>canManage(grant,t.id));}
function teamForm(id){const t=data.teams.find(x=>x.id===id);form(t?'Takımı düzenle':'Takım / birim oluştur',field('Ad *','name',t?.name,'text',true)+select('Tür','kind',t?.kind||'team',[['team','Yarışma takımı'],['unit','Çalışma birimi']])+select('Renk','color',t?.color||'blue',[['blue','Mavi'],['purple','Mor'],['orange','Turuncu'],['teal','Yeşil']])+area('Açıklama','description',t?.description,1000),async v=>{if(v.name.length<2)throw Error('Ad en az iki karakter olmalı.');await change('portalTeams/'+(id||crypto.randomUUID()),v,t?stamp(t.updatedAt):null,!t);});}
function memberForm(id){const m=data.members.find(x=>x.email===id),a=data.access.find(x=>x.id===id);form(id?'Üyeyi ve erişimi düzenle':'Üye ekle',field('Ad soyad *','name',m?.name,'text',true)+field('Google e-posta adresi *','email',id,'email',true,254)+select('Rol','role',a?.role||'member',Object.entries(ROLES))+select('Erişim','active',a?.active?'yes':'no',[['no','Kapalı'],['yes','Açık']])+field('Telefon','phone',m?.phone,'tel',false,40)+field('Görev / unvan','jobTitle',m?.jobTitle)+field('Üniversite','university',m?.university)+field('Bölüm','department',m?.department)+field('Sınıf','year',m?.year,'text',false,80)+`<div class="form-field wide"><span>Takımlar / birimler (en fazla 10)</span><div class="checkboxes">${data.teams.map(t=>`<label class="check"><input type="checkbox" name="teamIds" value="${E(t.id)}" ${m?.teamIds.includes(t.id)?'checked':''}>${E(t.name)}</label>`).join('')}</div></div>`+area('Üyenin ve takım sorumlusunun görebileceği not','notes',m?.notes)+`<p class="op-help wide">Google hesabındaki e-posta tam olarak eşleşmelidir. Bu işlem davet e-postası göndermez.</p>`,async(v,fd)=>{
  const address=v.email.toLowerCase(),teamIds=fd.getAll('teamIds');if(id&&address!==id)throw Error('E-posta kimliği değiştirilemez. Yeni adres için ayrı üyelik oluştur ve eski erişimi kapat.');if(v.name.length<2||!/^[^/@\s]+@[^/@\s]+\.[^/@\s]+$/.test(address))throw Error('Ad ve e-posta geçerli olmalı.');if(teamIds.length>10)throw Error('En fazla 10 takım seç.');if(OWNER_EMAILS.includes(address)&&(v.active!=='yes'||v.role!=='admin'))throw Error('Sistem sahibi hesabının erişimi veya rolü bu ekrandan değiştirilemez.');if(address===email()&&(v.active!=='yes'||v.role!=='admin'))throw Error('Kendi yönetici erişimini bu ekrandan kapatamazsın.');
  const token=epoch;await runTransaction(service.db,async tx=>{assertSession(token);const ar=doc(service.db,'portalAccess',address),mr=doc(service.db,'portalMembers',address),old=await tx.get(ar);if(!id&&old.exists())throw Error('Bu e-posta zaten kayıtlı.');if(id&&stamp(old.data()?.updatedAt)!==stamp(a?.updatedAt))throw Error('Üye erişimi değişmiş. Pencereyi yeniden aç.');const profile={name:v.name,email:address,phone:v.phone,university:v.university,department:v.department,year:v.year,jobTitle:v.jobTitle,notes:v.notes,teamIds,updatedAt:serverTimestamp()};tx.set(ar,{name:v.name,role:v.role,active:v.active==='yes',teamIds,updatedAt:serverTimestamp()});tx.set(mr,profile);});});if(id)$('form').elements.email.readOnly=true;}
function taskForm(id){const t=data.tasks.find(x=>x.id===id),teams=editableTeams();if(!t&&!teams.length){toast('Önce bir takım oluştur veya takım sorumluluğu ata.');return;}const full=!t||canManage(grant,t.teamId);let html=full?field('Görev adı *','title',t?.title,'text',true)+select('Takım','teamId',t?.teamId||teams[0]?.id,teams.map(t=>[t.id,t.name]))+select('Sorumlu','assignee',t?.assignee,activeMembers().map(m=>[m.email,m.name]))+field('Hedef tarih','due',t?.due,'date')+area('Görev açıklaması','description',t?.description):`<p class="op-muted wide">${E(t.title)}</p>`;html+=select('Durum','status',t?.status||'todo',Object.entries(STATUS))+area('Takıldığın yer / destek ihtiyacı','blocker',t?.blocker,1000)+area('Çıktı notu','evidence',t?.evidence)+field('Çıktı bağlantısı (isteğe bağlı)','evidenceUrl',t?.evidenceUrl,'url',false,1000);
  form(t?'Görevi güncelle':'Yeni görev',html,async v=>{if(v.status==='done'&&v.blocker)throw Error('Tamamlamadan önce engel açıklamasını temizle.');if(v.evidenceUrl&&!safeURL(v.evidenceUrl))throw Error('Bağlantı https:// veya http:// ile başlamalı.');if(full&&!activeMembers(v.teamId).some(m=>m.email===v.assignee))throw Error('Sorumlu seçilen takımın aktif üyesi olmalı.');if(!t)Object.assign(v,{createdAt:serverTimestamp(),lastCommentId:'',lastCommentBy:'',lastCommentAt:null});await change('portalTasks/'+(id||crypto.randomUUID()),v,t?stamp(t.updatedAt):null,!t);});}
let commentOff=null;
function taskDetail(id){const t=data.tasks.find(t=>t.id===id);if(!t)return;openModal(t.title,`<div class="op-meta">${tag(teamName(t.teamId))}${tag(STATUS[t.status],t.status)}</div><p class="op-muted" style="margin:16px 0">Sorumlu: ${E(personName(t.assignee))} · Hedef: ${date(t.due)}</p><p class="detail-text">${E(t.description)}</p>${t.blocker?`<p class="op-danger">${E(t.blocker)}</p>`:''}<div class="answer"><h3>Çıktı</h3><p>${E(t.evidence||'Henüz çıktı eklenmedi.')}</p>${safeURL(t.evidenceUrl)?`<a href="${E(safeURL(t.evidenceUrl))}" target="_blank" rel="noopener noreferrer" class="text-button">Çıktı bağlantısını aç ↗</a>`:''}</div>${button('Görevi güncelle','task-edit',id,true)}<h3 style="margin:25px 0 10px;font-size:16px">Görev konuşması</h3><div id="thread">Yorumlar yükleniyor…</div><form id="comment-form"><label class="form-field"><span>Yorumun</span><textarea name="body" required maxlength="2000" placeholder="Kısa bir güncelleme, soru veya çıktı bağlantısı…"></textarea></label><p class="error" id="form-error" role="alert"></p><div class="form-actions"><button class="btn primary" type="submit">Yorum ekle</button></div></form>`,'task',id);
  commentOff?.();const token=epoch;commentOff=onSnapshot(query(collection(service.db,'portalTasks',id,'comments'),orderBy('createdAt','desc'),limit(100)),{includeMetadataChanges:true},s=>{if(token!==epoch||modalMode!=='task'||modalId!==id||s.metadata.fromCache||s.metadata.hasPendingWrites)return;const list=s.docs.map(x=>x.data()).reverse();$('thread').innerHTML=list.map(c=>`<article class="comment"><strong>${E(personName(c.author))}</strong><small>${date(c.createdAt)}</small><p>${E(c.body)}</p></article>`).join('')||'<p class="op-muted">İlk güncellemeyi sen paylaş.</p>';if(list.length===100)$('thread').insertAdjacentHTML('afterbegin','<p class="op-help">En son 100 yorum gösteriliyor.</p>');},e=>{if(token===epoch)lock(errText(e));});subscriptions.push(()=>commentOff?.());}
async function addComment(body){if(!body.trim())throw Error('Bir yorum yaz.');const token=epoch,id=modalId,cr=doc(collection(service.db,'portalTasks',id,'comments'));await runTransaction(service.db,async tx=>{assertSession(token);const tr=doc(service.db,'portalTasks',id),t=await tx.get(tr);if(!t.exists())throw Error('Görev bulunamadı.');tx.set(cr,{author:email(),body:body.trim(),createdAt:serverTimestamp()});tx.update(tr,{lastCommentId:cr.id,lastCommentBy:email(),lastCommentAt:serverTimestamp()});});}
function routeForm(id){const r=data.routes.find(r=>r.id===id),teams=editableTeams();if(!teams.length){toast('Önce bir takım oluştur veya sorumluluk ata.');return;}form(r?'Öğrenme rotasını düzenle':'Öğrenme rotası oluştur',field('Rota adı *','name',r?.name,'text',true)+select('Takım','teamId',r?.teamId||teams[0].id,teams.map(t=>[t.id,t.name]))+area('Amaç','description',r?.description,1000)+area('Her satıra bir adım · En fazla 15 *','steps',r?.steps.join('\n'),4500),async v=>{const steps=v.steps.split('\n').map(x=>x.trim()).filter(Boolean);if(v.name.length<2||!steps.length||steps.length>15||steps.some(s=>s.length>300))throw Error('Rota adı ve 1–15 adım gerekli. Her adım en fazla 300 karakter olmalı.');await change('portalRoutes/'+(id||crypto.randomUUID()),{...v,steps},r?stamp(r.updatedAt):null,!r);});}
function enrollForm(routeId){const routes=data.routes.filter(r=>canManage(grant,r.teamId));if(!routes.length){toast('Önce takımın için bir öğrenme rotası oluştur.');return;}const mentors=admin()?data.access.filter(a=>a.active&&['admin','mentor'].includes(a.role)).map(a=>[a.id,a.name]):[[email(),grant.name]];form('Üyeye rota ata',select('Rota','routeId',routeId||routes[0].id,routes.map(r=>[r.id,r.name]))+select('Öğrenecek üye','memberEmail','',activeMembers().map(m=>[m.email,m.name]))+select('Mentor','mentorEmail',email(),mentors)+field('Hedef tarih *','due',plusDays(14),'date',true)+`<p class="op-help wide">Üye ve mentor rotanın takımında olmalı. Atanan adımlar şablondan kopyalanır; sonraki şablon düzenlemeleri bu atamayı değiştirmez.</p>`,async v=>{const r=routes.find(r=>r.id===v.routeId);if(v.memberEmail===v.mentorEmail)throw Error('Mentor ve öğrenen farklı kişiler olmalı.');if(v.due<localDay())throw Error('Hedef tarih geçmişte olamaz.');const id=v.memberEmail+'__'+r.id,token=epoch;await runTransaction(service.db,async tx=>{assertSession(token);const en=doc(service.db,'portalEnrollments',id),existing=await tx.get(en);if(existing.exists())throw Error('Bu rota bu üyeye daha önce atanmış.');tx.set(en,{name:r.name,routeId:r.id,teamId:r.teamId,memberEmail:v.memberEmail,mentorEmail:v.mentorEmail,due:v.due,stepCount:r.steps.length,createdAt:serverTimestamp()});r.steps.forEach((title,index)=>tx.set(doc(collection(en,'steps'),String(index)),{index,title,status:'todo',evidence:'',evidenceUrl:'',feedback:'',reviewerEmail:'',reviewedAt:null,updatedAt:serverTimestamp()}));});});}
function enrollmentDetail(id){const en=data.enrollments.find(e=>e.id===id);if(!en)return;const mine=en.memberEmail===email(),reviewer=(admin()||en.mentorEmail===email())&&!mine;openModal(en.name,`<p class="op-muted">Üye: ${E(personName(en.memberEmail))}<br>Mentor: ${E(personName(en.mentorEmail))} · Hedef: ${date(en.due)}</p>${(data.steps[id]||[]).map(s=>`<article class="step-card">${tag(`${s.index+1}. adım · ${{todo:'Çalışılıyor',pending:'İncelemede',done:'Onaylandı'}[s.status]}`,s.status)}<h3>${E(s.title)}</h3>${s.evidence?`<p><strong>Çıktı:</strong><br>${E(s.evidence)}</p>`:''}${safeURL(s.evidenceUrl)?`<a target="_blank" rel="noopener noreferrer" href="${E(safeURL(s.evidenceUrl))}">Çıktı bağlantısı ↗</a>`:''}${s.feedback?`<p><strong>Mentor notu:</strong> ${E(s.feedback)}</p>`:''}${s.reviewedAt?`<p class="op-help">${E(s.reviewerEmail)} · ${date(s.reviewedAt)}</p>`:''}<div class="actions">${mine&&s.status!=='done'?button('Çıktı ekle / düzenle','step-evidence',id+'|'+s.id,true):''}${reviewer&&s.status==='pending'?button('Değerlendir','step-review',id+'|'+s.id,true):''}</div></article>`).join('')||'<p class="op-help">Adımlar yükleniyor…</p>'}`,'enrollment',id);}
function stepForm(key,review){const [enId,sid]=key.split('|'),s=data.steps[enId]?.find(s=>s.id===sid);if(!s)return;form(review?'Mentor değerlendirmesi':'Çıktını paylaş',review?`<p class="detail-text wide">${E(s.evidence)}</p>`+select('Karar','status','done',[['done','Onayla'],['todo','Düzeltme iste']])+area('Geri bildirim · Düzeltmede zorunlu','feedback',s.feedback,2000):area(s.title+' · Çıktı notu *','evidence',s.evidence)+field('Çıktı bağlantısı (isteğe bağlı)','evidenceUrl',s.evidenceUrl,'url',false,1000),async v=>{if(review){if(v.status==='todo'&&!v.feedback)throw Error('Düzeltme isteğini açıkla.');Object.assign(v,{reviewerEmail:email(),reviewedAt:serverTimestamp()});}else{if(v.evidence.length<5)throw Error('En az 5 karakterlik çıktı notu ekle.');if(v.evidenceUrl&&!safeURL(v.evidenceUrl))throw Error('Geçerli bir web bağlantısı gir.');v.status='pending';}await change(`portalEnrollments/${enId}/steps/${sid}`,v,stamp(s.updatedAt));});}
function assetForm(id){const a=data.equipment.find(a=>a.id===id);form(a?'Ekipman bilgileri':'Ekipman ekle',field('Ad *','name',a?.name,'text',true)+field('Envanter kodu *','code',a?.code,'text',true,100)+field('Konum','location',a?.location)+select('Teknik durum','condition',a?.condition||'ready',[['ready','Hazır'],['maintenance','Bakımda']])+area('Not','note',a?.note,1000),async v=>{v.code=v.code.toUpperCase();if(!/^[A-Z0-9_-]{1,100}$/.test(v.code))throw Error('Kod için A–Z, 0–9, - ve _ kullan.');if(id&&v.code!==id)throw Error('Envanter kodu sonradan değiştirilemez.');if(!a)v.activeLoanId='';await change('portalEquipment/'+v.code,v,a?stamp(a.updatedAt):null,!a);});if(a)$('form').elements.code.readOnly=true;}
function assetDetail(id){const a=data.equipment.find(a=>a.id===id);if(!a)return;const list=data.loans.filter(l=>l.equipmentId===id).sort((a,b)=>stamp(b.issuedAt)-stamp(a.issuedAt));openModal(a.name,`<span class="asset-code">${E(a.code)}</span><p class="op-muted" style="margin:15px 0">${E(a.location)} · ${a.condition==='ready'?'Hazır':'Bakımda'}</p><p class="detail-text">${E(a.note)}</p>${admin()?button('Bilgileri düzenle','asset-edit',id):''}<h3 style="margin:22px 0 12px;font-size:16px">${admin()?'Teslim / iade geçmişi':'Sana ait teslim / iade kayıtları'}</h3><ol class="op-timeline">${list.map(l=>`<li><strong>${E(l.memberName)}</strong><p>Teslim: ${date(l.issuedAt)} · Hedef: ${date(l.due)}<br>${E(l.purpose)}</p>${l.returnedAt?`<p>İade: ${date(l.returnedAt)} · ${l.returnCondition==='ready'?'Hazır':'Bakımda'}<br>${E(l.returnNote)}</p>`:tag(l.returnRequested?'İade talep edildi':'Zimmette','pending')}</li>`).join('')||'<li>Görüntülenebilir kayıt yok.</li>'}</ol>`,'asset',id);}
function loanForm(id){const a=data.equipment.find(a=>a.id===id);if(!a||a.activeLoanId||a.condition!=='ready'){toast('Ekipman zimmet verilmeye uygun değil.');return;}form(a.name+' · Teslim',select('Teslim alan','memberEmail','',activeMembers().map(m=>[m.email,m.name]))+field('İade tarihi *','due',plusDays(7),'date',true)+area('Teslim / kullanım notu *','purpose','',1000),async v=>{if(v.due<localDay()||!v.purpose)throw Error('İade tarihi ve kullanım notunu kontrol et.');const token=epoch,lr=doc(collection(service.db,'portalLoans'));await runTransaction(service.db,async tx=>{assertSession(token);const ar=doc(service.db,'portalEquipment',id),snapshot=await tx.get(ar);if(!snapshot.exists()||snapshot.data().activeLoanId||snapshot.data().condition!=='ready')throw Error('Bu ekipman başka bir işlemle zimmetlenmiş veya bakıma alınmış.');tx.set(lr,{equipmentId:id,equipmentName:snapshot.data().name,memberEmail:v.memberEmail,memberName:personName(v.memberEmail),due:v.due,purpose:v.purpose,issuedAt:serverTimestamp(),returnRequested:false,returnedAt:null,returnNote:'',returnCondition:''});tx.update(ar,{activeLoanId:lr.id,updatedAt:serverTimestamp()});});});}
function returnForm(id){const l=data.loans.find(l=>l.id===id&&!l.returnedAt);if(!l)return;form('Ekipmanı teslim al',`<p class="op-muted wide">${E(l.memberName)} · ${E(l.equipmentName)}</p>`+select('İade durumu','condition','ready',[['ready','Hazır / kullanılabilir'],['maintenance','Bakım gerekiyor']])+area('İade / hasar notu','note','',1000),async v=>{if(v.condition==='maintenance'&&!v.note)throw Error('Bakım ihtiyacını açıkla.');const token=epoch;await runTransaction(service.db,async tx=>{assertSession(token);const lr=doc(service.db,'portalLoans',id),ar=doc(service.db,'portalEquipment',l.equipmentId),ls=await tx.get(lr),as=await tx.get(ar);if(ls.data()?.returnedAt||as.data()?.activeLoanId!==id)throw Error('Bu zimmet artık aktif değil.');tx.update(lr,{returnedAt:serverTimestamp(),returnNote:v.note,returnCondition:v.condition});tx.update(ar,{activeLoanId:'',condition:v.condition,updatedAt:serverTimestamp()});});});}
async function requestReturn(id){const token=epoch;await runTransaction(service.db,async tx=>{assertSession(token);const r=doc(service.db,'portalLoans',id),s=await tx.get(r);if(!s.exists()||s.data().returnedAt)throw Error('Zimmet aktif değil.');tx.update(r,{returnRequested:true});});}
function refreshDetail(){if(!$('modal').open||busy)return;if(modalMode==='enrollment')enrollmentDetail(modalId);if(modalMode==='asset')assetDetail(modalId);}
async function bootstrap(){if(!OWNER_EMAILS.includes(email()))throw Error('Sistem sahibi hesabı gerekli.');const token=epoch,teams=teamDefaults(),accounts=[['rmzazakli@gmail.com','Remzi Azaklı'],['remziazakli@gmail.com','Remzi Azaklı'],['sudenzturk@gmail.com','Sude Naz Türk']];const routes=[{id:'start-ai',teamId:'ai',name:'Görüntü işlemede ilk adım',description:'Kurulumdan ölçülebilir bir çıktıya.',steps:['Geliştirme ortamını kur ve notlarını paylaş','Örnek görüntü üzerinde basit bir işlem uygula','Beklenen ve ölçülen sonucu karşılaştır','Çıktını mentorunla değerlendir']},{id:'start-ew',teamId:'ew',name:'Elektronik laboratuvarına giriş',description:'Güvenli çalışma ve temel ölçüm kaydı.',steps:['Laboratuvar güvenliğini mentorla gözden geçir','Devre şemasını ve parça listesini hazırla','Mentor gözetiminde temel ölçümü kaydet','Şema ile ölçümü karşılaştır']},{id:'start-uav',teamId:'uav',name:'Tasarımdan ilk modele',description:'Gereksinimden üretilebilir bir parçaya.',steps:['Parçanın amacını, ölçülerini ve kısıtlarını yaz','İlk CAD modelini hazırla','Ölçüleri ve üretilebilirliği kontrol et','Modeli ve tasarım notunu paylaş']}];
  await runTransaction(service.db,async tx=>{assertSession(token);const records=[...teams.map(({id,...t})=>['portalTeams/'+id,{...t,updatedAt:serverTimestamp()}]),...routes.map(({id,...r})=>['portalRoutes/'+id,{...r,updatedAt:serverTimestamp()}])];for(const [address,name] of accounts){records.push(['portalAccess/'+address,{name,role:'admin',teamIds:teams.map(t=>t.id),active:true,updatedAt:serverTimestamp()}]);records.push(['portalMembers/'+address,{name,email:address,phone:'',university:'',department:'',year:'',jobTitle:'Yönetici',notes:'',teamIds:teams.map(t=>t.id),updatedAt:serverTimestamp()}]);}const snapshots=await Promise.all(records.map(([path])=>tx.get(ref(path))));for(let i=0;i<records.length;i++)if(!snapshots[i].exists())tx.set(ref(records[i][0]),records[i][1]);});}
async function markRead(id){const token=epoch;await runTransaction(service.db,async tx=>{assertSession(token);tx.set(doc(service.db,'portalSeen',email(),'items',id),{seenAt:serverTimestamp()});});}
async function allDocs(path,token){const out=[];let after=null;for(;;){assertSession(token);const q=query(collection(service.db,...path.split('/')),orderBy(documentId()),...(after?[startAfter(after)]:[]),limit(100)),s=await getDocsFromServer(q);assertSession(token);out.push(...s.docs.map(d=>({id:d.id,...d.data()})));if(s.size<100)break;after=s.docs.at(-1);}return out;}
async function backup(){const token=epoch;assertSession(token);await recheck();const out={};for(const name of ['Access','Members','Teams','Tasks','Routes','Enrollments','Equipment','Loans'])out[name]=await allDocs('portal'+name,token);out.comments={};for(const t of out.Tasks)out.comments[t.id]=await allDocs('portalTasks/'+t.id+'/comments',token);out.steps={};for(const e of out.Enrollments)out.steps[e.id]=await allDocs('portalEnrollments/'+e.id+'/steps',token);assertSession(token);download({app:'ARVUS-CLOUD',version:1,project:'arvus-basvuru',exportedAt:new Date().toISOString(),data:out},'ARVUS-Ortak-Yedek');}
function download(value,name){const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name+'-'+localDay()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
async function importApplications(file){if(!file)return;if(file.size>20000000)throw Error('Dosya 20 MB sınırını aşıyor.');const json=JSON.parse((await file.text()).replace(/^\uFEFF/,''));if(json.app!=='ARVUS-APPLICATIONS'||json.version!==1||json.source!=='arvus-basvuru'||!Array.isArray(json.applications)||json.applications.length>10000)throw Error('Başvuru panelinden alınan JSON dosyasını seç.');const people=new Map();for(const a of json.applications){if(typeof a.email!=='string'||typeof a.fullName!=='string'||!/^\S+@\S+\.\S+$/.test(a.email)||a.fullName.length>160||a.email.length>254)throw Error('Dosyada geçersiz başvuru var.');const address=a.email.trim().toLowerCase(),team=['ai','ew','uav','other'].includes(a.category)?a.category:'other';let p=people.get(address);if(!p){p={name:a.fullName.trim(),email:address,phone:String(a.phone||'').slice(0,40),university:String(a.university||'').slice(0,160),department:String(a.department||'').slice(0,160),year:String(a.year||'').slice(0,80),jobTitle:'Üye',notes:'Başvuru dosyasından aktarıldı. Orijinal yanıtlar başvuru panelindedir.',teamIds:[]};people.set(address,p);}if(data.teams.some(t=>t.id===team)&&!p.teamIds.includes(team))p.teamIds.push(team);}
  const rows=[...people.values()];form('Başvuru aktarımını onayla',`<p class="op-muted wide">${rows.length} benzersiz e-posta kontrol edilecek. Yeni kişiler erişimi kapalı olarak eklenir; mevcut kayıtlar korunur. Orijinal başvuru yanıtları başvuru panelinde kalır.</p>`,async()=>{const token=epoch;let added=0;for(const p of rows){assertSession(token);const did=await runTransaction(service.db,async tx=>{assertSession(token);const ar=doc(service.db,'portalAccess',p.email),mr=doc(service.db,'portalMembers',p.email),old=await tx.get(ar),member=await tx.get(mr);if(old.exists()||member.exists())return false;tx.set(ar,{name:p.name,role:'member',teamIds:p.teamIds,active:false,updatedAt:serverTimestamp()});tx.set(mr,{...p,updatedAt:serverTimestamp()});return true;});if(did)added++;}toast(`${added} yeni kişi eklendi.`);});}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||busy)return;if(b.dataset.nav){go(b.dataset.nav);return;}const act=b.dataset.action,id=b.dataset.id;try{
  if(act==='modal-close'){$('modal').close();modalMode='';return;}
  if(act==='task-new')taskForm();if(act==='task-open')taskDetail(id);if(act==='task-edit')taskForm(id);
  if(act==='member-new')memberForm();if(act==='member-edit')memberForm(id);if(act==='member-open'){const m=data.members.find(m=>m.email===id);openModal(m.name,`<dl class="detail-grid">${[['E-posta',m.email],['Telefon',m.phone],['Üniversite',m.university],['Bölüm',m.department],['Sınıf',m.year],['Görev',m.jobTitle]].map(([k,v])=>`<div><dt>${k}</dt><dd>${E(v||'—')}</dd></div>`).join('')}</dl><p class="detail-text">${E(m.notes)}</p>`);}
  if(act==='team-new')teamForm();if(act==='team-edit')teamForm(id);if(act==='route-new')routeForm();if(act==='route-edit')routeForm(id);if(act==='enroll-new')enrollForm(id);if(act==='enroll-open')enrollmentDetail(id);if(act==='step-evidence')stepForm(id,false);if(act==='step-review')stepForm(id,true);
  if(act==='asset-new')assetForm();if(act==='asset-edit')assetForm(id);if(act==='asset-open')assetDetail(id);if(act==='loan-new')loanForm(id);if(act==='loan-return')returnForm(id);if(act==='return-request')await execute(()=>requestReturn(id),false);
  if(act==='bootstrap')await execute(bootstrap,false);if(act==='backup')await execute(backup,false);if(act==='goto-members')go('members');if(act==='import-apps')$('applications-file').click();
  if(act==='notice-read')await execute(()=>markRead(id),false);if(act==='notice-open'){const n=notices(data,email(),admin()).find(n=>n.id===id);if(n){await execute(()=>markRead(id),false);if(!grant)return;if(n.target.kind==='task')taskDetail(n.target.id);else if(n.target.kind==='enrollment')enrollmentDetail(n.target.id);else go('equipment');}}
  if(act==='load-more'){cap=Math.min(2000,cap+200);startData(grant);}
}catch(err){toast(errText(err));}});
document.addEventListener('submit',async e=>{if(e.target.id==='form'){e.preventDefault();const fd=new FormData(e.target),values=Object.fromEntries(fd);for(const k of Object.keys(values))values[k]=String(values[k]).trim();if(formAction)await execute(()=>formAction(values,fd));}if(e.target.id==='comment-form'){e.preventDefault();const body=new FormData(e.target).get('body');const ok=await execute(()=>addComment(body),false);if(ok&&$('comment-form'))$('comment-form').reset();}});
document.addEventListener('input',e=>{if(e.target.id==='search'){const pos=e.target.selectionStart;search=e.target.value;render();$('search').focus();$('search').setSelectionRange(pos,pos);}});
document.addEventListener('change',e=>{if(e.target.id==='filter'){filter=e.target.value;render();}if(e.target.id==='applications-file')importApplications(e.target.files[0]).catch(e=>toast(errText(e)));});
$('close-modal').onclick=()=>{if(!busy)$('modal').close();};$('modal').addEventListener('cancel',e=>{if(busy)e.preventDefault();});$('modal').addEventListener('close',()=>{commentOff?.();commentOff=null;modalMode='';modalId='';formAction=null;});$('mobile-toggle').onclick=()=>$('sidebar').classList.toggle('open');
$('logout').onclick=$('auth-logout').onclick=async()=>{grantOff?.();grantOff=null;stopData();user=null;gate('Çıkış yapılıyor…');await service.logout();gate('Takıma kayıtlı Google hesabınla giriş yap.');};
$('login').onclick=async()=>{try{$('login').disabled=true;if(user){await recheck();}else await service.login();}catch(e){gate(errText(e),!!user);if(e.code==='auth/popup-blocked')$('redirect-login').hidden=false;}finally{$('login').disabled=false;}};
$('redirect-login').onclick=()=>service.redirect().catch(e=>gate(errText(e)));
window.addEventListener('hashchange',()=>{if(grant&&location.hash.slice(1)!==view)go(location.hash.slice(1));});window.addEventListener('offline',()=>{if(user)lock('İnternet bağlantısı kesildi. Kayıtları görmek ve değiştirmek için yeniden bağlan.');});window.addEventListener('online',()=>recheck().catch(e=>lock(errText(e))));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&user)recheck().catch(e=>lock(errText(e)));});
view=location.hash.slice(1)||'today';
connect().then(async s=>{service=s;gate('Takıma kayıtlı Google hesabınla giriş yap.');s.observe(attachUser);try{await s.redirectResult();}catch(e){gate(errText(e));}}).catch(e=>gate(errText(e)));
